/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.launchableinc.rocket_car_gradle;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test void testAppHasAGreeting2() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Nested
    class Inner() {
        @Test void testAppHasAGreeting3() {
            App classUnderTest = new App();
            assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        }
        @Test void testAppHasAGreeting4() {
            App classUnderTest = new App();
            assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        }
    }
}
