/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sample_app_gradle.sub;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions.*;
import com.example.sample_app_gradle.App;

public class App3Test {
    @Test void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test void testAppHasAGreeting2() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

}
